### ISSUE TITLE
Some past EABI notes

### ISSUE THREAD

**Issue by ilg-ul** [riscv/riscv-eabi-spec#4]
From past discussions, I collected some comments that I also copy here, to be checked:

- [AW] For RVC compressibility, the most popular registers should be x8-x15. So I suggest renumbering x8/x9 to be s0/s1 (as is the case in the POSIX ABI).
- [AW] Per the ISA spec, x5 serves as an alternate link register, to drive hardware management of return-address stacks. It’s used by things like the -msave-restore option, which reduces code size by using millicode routines to implement prologues/epilogues. For this to work, x5 needs to be one of the t-registers, as is the case in the POSIX ABI. I suggest either adding one more t-register at x5, or moving an existing t-register to x5. (The former option is better for code size and performance; the latter option is better for interrupt latency.)
- [AW] For all the use cases I’ve encountered, two t-registers is sufficient for linkage purposes.
- [BH] jal[r] and jr with x5 are being baked into hardware as function call/return, just as with x1, complete with a special return address stack to accelerate the indirect jump for function return. That's especially important with millicode register save/restore which will primarily be used on microcontrollers. So x5 must be a t register. No choice. But maybe don't call it t0, if at least one t register is in x8-x15.
- [BH] the lowest numbered registers of each class (s, a t) should fall somewhere inside the C-favoured registers x8-x15 (if any registers of that class fall in this range).

**Comment by kasanovic** [comment]
These issues are all addressed in current draft, except that temporaries are t0 mapped to x5 and t1 to x15, which does not have lowest numbered temporary in RVC-favored registers.  This was to minimize change/surprise from existing UABI.

**Comment by ilg-ul** [comment]
If @aswaterman and Bruce (I don't know his GH id) have no further comments, and the validation suites do not reveal any surprises, this is fine with me.

**Comment by kasanovic** [comment]
Closing this as it appears issues are settled.
