### ISSUE TITLE
4 arguments register may be a perf. issue for 64 bits type

### ISSUE THREAD

**Issue by soberl** [riscv/riscv-eabi-spec#8]
How about to merge temporary registers to arguments registers?

**Comment by kasanovic** [comment]
I believe there needs to be at least two temporaries that are not part of the argument registers for some linkage conventions to work - deferring to others on this issue.

**Comment by soberl** [comment]
Get it. I realize that the point here is x0-x4 take away 5 GPR away, so 4 arguments registers sounds reasonable. Thanks.
